### ISSUE TITLE
Doc type for DTS

### ISSUE THREAD

**Issue by gabays** [katabase/1_OutputData#4]
We are missing an attribute in the TEI file for the DTS collections. Possible values (=type of catalogues):
* RDA
* LAD
* AUC
* LAV
* UNK

**Comment by alexbartz** [comment]
We decided to add a new taxonomy containing informations about the type of catalogues with an XSL stylesheet (see [here](https://github.com/katabase/Data_extraction/tree/master/_transformations) `step_1_auction.xsl` and `step_1_fixedPrice.xsl`. 

As a reminder :
* RDA : Revue des autographes, des curiosités de l'histoire et de la biographie
* LAD : Lettres autographes et documents historiques
* AUC : Vente aux enchères
* LAV : Ventes Laverdet
* OTH (and not UNK) : Divers/inconnus

I close the issue.
